Parameters:
  RepositoryName:
    Description: ECR repository name
    Type: String

Resources:
  RubyEcr:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref 'RepositoryName'

Outputs:
  RubyEcrUrl:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}"
